# Form implementation generated from reading ui file '/Volumes/KINGSTON/Dev/python/python.my-manager/ui/dialog_robot_run.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_RobotRun(object):
    def setupUi(self, Dialog_RobotRun):
        Dialog_RobotRun.setObjectName("Dialog_RobotRun")
        Dialog_RobotRun.resize(480, 167)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog_RobotRun)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.thread_container_layout = QtWidgets.QHBoxLayout()
        self.thread_container_layout.setObjectName("thread_container_layout")
        self.thread_input = QtWidgets.QSpinBox(parent=Dialog_RobotRun)
        self.thread_input.setObjectName("thread_input")
        self.thread_container_layout.addWidget(self.thread_input)
        self.thread_label = QtWidgets.QLabel(parent=Dialog_RobotRun)
        self.thread_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.thread_label.setObjectName("thread_label")
        self.thread_container_layout.addWidget(self.thread_label)
        self.verticalLayout_2.addLayout(self.thread_container_layout)
        self.progress_container_layout = QtWidgets.QVBoxLayout()
        self.progress_container_layout.setObjectName("progress_container_layout")
        self.progressBar = QtWidgets.QProgressBar(parent=Dialog_RobotRun)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.progress_container_layout.addWidget(self.progressBar)
        self.progress_message_label = QtWidgets.QLabel(parent=Dialog_RobotRun)
        self.progress_message_label.setObjectName("progress_message_label")
        self.progress_container_layout.addWidget(self.progress_message_label)
        self.verticalLayout_2.addLayout(self.progress_container_layout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog_RobotRun)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_RobotRun)
        self.buttonBox.accepted.connect(Dialog_RobotRun.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_RobotRun.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_RobotRun)

    def retranslateUi(self, Dialog_RobotRun):
        _translate = QtCore.QCoreApplication.translate
        Dialog_RobotRun.setWindowTitle(_translate("Dialog_RobotRun", "Dialog"))
        self.thread_label.setText(_translate("Dialog_RobotRun", "Thread num"))
        self.progress_message_label.setText(_translate("Dialog_RobotRun", "Progress message"))
